CicloviaProgram/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views

from CicloviaProgram import views

urlpatterns = patterns('',
                    # Páginas principales.
    url(r'^$', views.index, name='index'),
    url(r'^models/$', views.userModels, name='userModels'),
    url(r'^(?P<ciclovia_id>\d+)/$', views.detail, name='detail'),
    url(r'^editCiclovia/(?P<ciclovia_id>\d+)/$', views.editCiclovia, name='editCiclovia'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^uploadFormCiclovia$', views.uploadFormCiclovia, name='uploadFormCiclovia'),
    url(r'^copyCiclovia/(?P<ciclovia_id>\d+)$', views.copiarCiclovia, name='copyCiclovia'),
    url(r'^borrarCiclovia/(?P<ciclovia_id>\d+)/$', views.deleteCiclovia, name='borrarCiclovia'),
    url(r'^(?P<ciclovia_id>\d+)/(?P<track_id>\d+)/$',
        views.detailNeighboor, name='detailNeighboor'),
    url(r'^editNeighboor/(?P<ciclovia_id>\d+)/(?P<track_id>\d+)/$',
        views.editNeighboor, name='editNeighboor'),
    url(r'^(?P<ciclovia_id>\d+)/uploadArrivalInfo/$',
        views.uploadArrivalInfo, name='uploadArrivalInfo'),
    url(r'^(?P<ciclovia_id>\d+)/uploadArrivalInfoForm/$',
        views.uploadArrivalInfoForm, name='uploadArrivalInfoForm'),
    url(r'^(?P<ciclovia_id>\d+)/detailArrival$',
        views.detailArrival, name='detailArrival'),
    url(r'^(?P<ciclovia_id>\d+)/editArrivalInfo$',views.editArrivalInfo, name="editArrivalInfo"),
    # url(r'^adminSimulation/$', views.adminSimulation, name='adminSimulation'),
                       # Páginas de simulación
    url(r'^(?P<ciclovia_id>\d+)/simulationResults/$',
        views.simulationResults, name='simulationResults'),
    url(r'^simulationResultsOld/(?P<ciclovia_id>\d+)/$',
        views.simulationResultsOld, name='simulationResultsOld'),
    url(r'^simulationList$', views.simulationList, name='simulationList'),
    url(r'^compareSimulations$', views.compareSimulations, name='compareSimulations'),
                       # Páginas de validación
    url(r'^(?P<ciclovia_id>\d+)/simulationResultsValidation/$',
        views.simulationResultsValidation, name='simulationResultsValidation'),
    url(r'^(?P<ciclovia_id>\d+)/simulationResultsValidationOld/$',
        views.simulationResultsValidationOld, name='simulationResultsValidationOld'),
    url(r'^(?P<ciclovia_id>\d+)/simulationResultsValidationPerTrack'+
        '/(?P<track_id>\d+)/$', views.detailTrackValidation,
        name='detailTrackValidation'),
    url(r'^(?P<ciclovia_id>\d+)/simulationResultsValidationOneRun'+
        '/(?P<run_id>\d+)/$', views.detailValidationSingleRun,
        name='detailValidationSingleRun'),
    url(r'^(?P<ciclovia_id>\d+)/simulationResultsValidationOneRun'+
        '/(?P<run_id>\d+)/(?P<track_id>\d+)/$',
        views.detailTrackValidationSingleRun,
        name='detailTrackValidationSingleRun'),
                       #Paginas de simulación inversa
    url(r'^(?P<ciclovia_id>\d+)/inverseSimulation/$', views.inverseSimulationWarning,
        name='inverseSimulation'),
    url(r'^(?P<ciclovia_id>\d+)/inverseSimulationExecution/$',
        views.inverseSimulationExecution, name='inverseSimulationExecution'),
                       # Gráficas
    url(r'^charts/pie/$',views.piechart, name='pieChart'),
    url(r'^charts/verticalBarChart/$',views.verticalBarChart, name='vBarChart'),
    url(r'^charts/graph/$',views.graphImg, name='graph'),
                    # Páginas de usuario.
    url(r'^login$', auth_views.login,
        {'template_name':'ciclovia/login.html'}, name='login'),
    url(r'^newUser$', views.newUser, name='newUser'),
    url(r'^user$', views.user, name='user'),
    url(r'^changePassword$',auth_views.password_change,
        {'template_name':'ciclovia/cambiarContrasena.html',
         'post_change_redirect':'CicloviaProgram:cambiarContrasenaExito'}, name="cambiarContrasena"),
    url(r'^changePasswordSuccess$', auth_views.password_change_done,
        {'template_name':'ciclovia/cambiarContrasenaExito.html'}, name='cambiarContrasenaExito'),
    url(r'^passwordReset$', auth_views.password_reset, {'template_name':'ciclovia/passwordReset.html'
        ,'email_template_name':'ciclovia/passwordResetEmail.html','subject_template_name':'ciclovia/passwordResetSubject.txt'
        ,'post_reset_redirect':'CicloviaProgram:passwordResetDone',}, name='passwordReset'),
    url(r'^passwordResetDone$',auth_views.password_reset_done, {'template_name':'ciclovia/passwordResetDone.html'},
        name='passwordResetDone'),
    url(r'^passwordResetConfirm/(?P<uidb64>.+)/(?P<token>.+)$',auth_views.password_reset_confirm,
        {'template_name':'ciclovia/passwordResetConfirm.html', 'post_reset_redirect':'CicloviaProgram:passwordResetComplete'}
        , name='passwordResetConfirm'),
    url(r'^passwordResetComplete$',auth_views.password_reset_complete,
        {'template_name':'ciclovia/passwordResetComplete.html'}, name='passwordResetComplete'),
)

myCicloviaProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^CicloviaProgram/', include('CicloviaProgram.urls',
        namespace='CicloviaProgram')),
]

CicloviaProgram/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# This section contains the objects associated with the information of the structure of the Ciclovia
# - 1 - Ciclovia: contains the general information of the Ciclovia
# - 2 - Track: contains the main information of a track that belongs to a Ciclovia
# - 3 - NeighboorInfo: contains the relations between the tracks 
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# This object represents a Ciclovia
class Ciclovia(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=30)
    place = models.CharField(max_length=20)
    start_hour = models.FloatField(default=0)
    end_hour = models.FloatField(default=0)
    num_tracks = models.IntegerField(default=1)
    reference_track = models.IntegerField(default=0)
    reference_hour = models.IntegerField(default=0)
    reference_arrival_rate = models.FloatField(default=0)    
    arrivals_loaded = models.BooleanField(default=False)
        
    def __unicode__(self):  
        return self.name + " " + self.user.username


# This object represents a Track
class Track(models.Model):
    ciclovia = models.ForeignKey(Ciclovia)
    id_track = models.IntegerField(default=100)
    distance = models.FloatField(default=1)
    probability = models.FloatField(default=1)
    hasCountPoint = models.BooleanField(default=False)
    # Modified probabilities
    probabilityBegin = models.FloatField(default=1)
    probabilityEnd = models.FloatField(default=1)
    arrival_proportion = models.FloatField(default=1)

    # New Velocity parameters
    number_of_semaphores = models.IntegerField(default=1)
    # 0: no slope, 1: has middle slope, 2: high slope
    hasSlope = models.IntegerField(default=1)
    quality_of_track = models.IntegerField(default=1)

    def __unicode__(self):  
        return str(self.id_track)   


# This object represents the relation between two tracks
class NeighboorInfo(models.Model):
    track = models.ForeignKey(Track)
    neighboorId = models.IntegerField(default=1)
    probability = models.FloatField(default=1)
    direction = models.CharField(max_length=10)   
    fromDirection = models.CharField(max_length=10)   
    
    def __unicode__(self):  
        return str(self.neighboorId) + "," + str(self.probability)   

# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# This section contains the objects associated with the information of the arrivals' behavior
# - 1 - ParticipantType: contains the information related to the types of activities that people do in a Ciclovia
# - 2 - TimeInSystemDistribution: contains the information of the distribution of the time in system
# - 3 - ArrivalsProportionPerHour: contains the relative proportion of arrivals that occur in an hour
# - 4 - Document: contains the location of the XML files with the documents of the structure and the arrivals
#       of the Ciclovia
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


# This object represents a Type of participant
class ParticipantType(models.Model):
    ciclovia = models.ForeignKey(Ciclovia)
    activity = models.CharField(max_length=30)
    velocity = models.FloatField(default=1)
    percentage = models.FloatField(default=1)
       
    def __unicode__(self):  
        return self.activity
    

# This object represents one of the values of the time in system distribution
class TimeInSystemDistribution(models.Model):
    ciclovia = models.ForeignKey(Ciclovia)
    time = models.FloatField(default=1)
    percentage = models.FloatField(default=1)
       
    def __unicode__(self):  
        return str(self.time)
    

# This object represents one of the values of the time in system distribution
class ArrivalsProportionPerHour(models.Model):
    ciclovia = models.ForeignKey(Ciclovia)
    hour = models.FloatField(default=1)
    proportion = models.FloatField(default=1)
       
    def __unicode__(self):  
        return str(self.hour)


# This object represents the XML document which contains the information of a Ciclovia
class Document(models.Model):
    filename = models.CharField(max_length=100)
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')    
    
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# This section contains the objects associated with the information of the simulation
# - 1 - SimulationParameters: contains the information related to the specific details for simulation's execution
# - 2 - SimulationResultsCompiled: contains the statistics of a serie of runs
# - 3 - SimulationResults: contains the statistics of a single run
# - 4 - SimulationResultsCompiledPerTrack: contains the statistics of a serie of runs for a single track 
# - 5 - SimulationResultsPerTrack: contains the statistics of a single run in a specific track
# - 6 - SimulationResultsCompiledFlowPerTrack: contains the statistics associated to the flow of a serie of runs
#       for a single track
# - 7 - SimulationResultsFlowPerTrack: contains the statistics associated to the flow of a single run in a
#       specific track
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


# This object represents default information of the simulation
class SimulationParameters(models.Model):
    replications = models.FloatField(default=1)
    arrivals_probability_distribution = models.CharField(max_length=30)
               
    def __unicode__(self):  
        return str(self.replications) + "," + str(self.arrivals_probability_distribution)


# This object represents the statistics for a serie of runs
class SimulationResultsCompiled(models.Model):
    ciclovia = models.ForeignKey(Ciclovia)
    date = models.DateTimeField('date executed')
    num_runs = models.FloatField(default=0)
    avg_total_arrivals = models.IntegerField(default=0)
    stdev_total_arrivals = models.IntegerField(default=0)
    hw_total_arrivals = models.IntegerField(default=0)   
    average_number_system = models.FloatField(default=0)
    stdev_number_system = models.FloatField(default=0)
    hw_number_system = models.FloatField(default=0)
    is_validation = models.BooleanField(default=False)
    
    def __unicode__(self):  
        return 'Fecha: ' + self.date.strftime('%Y-%m-%d %H:%M %Z') + ', Replicas: ' + str(self.num_runs)


# This obhect represents the results of a single run
class SimulationResults(models.Model):
    ciclovia = models.ForeignKey(SimulationResultsCompiled)
    date = models.DateTimeField('date executed')
    sim_time = models.FloatField(default=0)
    total_arrivals = models.IntegerField(default=0)
    average_time = models.FloatField(default=0)
    standard_deviation_time = models.FloatField(default=0)
    average_number_system = models.FloatField(default=0)
    is_validation = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.sim_time) + "," + str(self.total_arrivals)


# This object represents the statistics per track for a serie of runs
class SimulationResultsCompiledPerTrack(models.Model):
    simulation_compiled = models.ForeignKey(SimulationResultsCompiled)
    track = models.IntegerField(default=0)
    average_number_track = models.IntegerField(default=0)
    stdev_number_track = models.IntegerField(default=0)
    hw_number_track = models.IntegerField(default=0)
    average_total_arrivals = models.IntegerField(default=0)
    stdev_total_arrivals = models.IntegerField(default=0)
    hw_total_arrivals = models.IntegerField(default=0)
    average_total_flow = models.IntegerField(default=0)
    stdev_total_flow = models.IntegerField(default=0)
    hw_total_flow = models.IntegerField(default=0)
    
    def __unicode__(self):  
        return str(self.simulation_compiled) + "," + str(self.track) + "," + str(self.average_number_track) + "," \
         + str(self.stdev_number_track) + "," + str(self.average_total_flow) + "," + str(self.stdev_total_flow)


# This object represents the information associated with the flow that occurs in a single track
class SimulationResultsPerTrack(models.Model):
    simulation = models.ForeignKey(SimulationResults)
    track = models.IntegerField(default=0)
    total_arrivals = models.IntegerField(default=0)
    total_flow = models.FloatField(default=0)
    average_number_track = models.IntegerField(default=0)
    
    def __unicode__(self):  
        return str(self.simulation) + "," + str(self.track) + "," + str(self.total_arrivals)


# This object represents the information associated with the flow of the track in a signle run
class SimulationResultsCompiledFlowTrack(models.Model):
    track_simulation = models.ForeignKey(SimulationResultsCompiledPerTrack)
    hour = models.IntegerField(default=0)
    avg_flow_hour = models.FloatField(default=0)
    stdev_flow_hour = models.FloatField(default=0)
    hw_flow_hour = models.FloatField(default=0)
            
    def __unicode__(self):  
        return str(self.track_simulation) + "," + str(self.hour) + "," + str(self.avg_flow_hour)


# This object represents the information associated with the flow of the track in a signle run
class SimulationResultsFlowPerTrack(models.Model):

CicloviaProgram/forms.py
# coding=utf-8
from django import forms
from django.utils.translation import ugettext_lazy as _

from models import *


class UploadForm(forms.Form):
    filename = forms.CharField(max_length=100, label='Nombre del archivo')
    docfile = forms.FileField(
        label='Selecciona un archivo'
    )

class NewUserForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ('username','email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    def clean_username(self):
        if len(User.objects.filter(username=self.cleaned_data['username'])) is not 0:
            raise forms.ValidationError(_('user already exists.'),code='used username')

        return self.cleaned_data['username']

    def clean_email(self):
        if len(User.objects.filter(email=self.cleaned_data['email'])) is not 0:
            raise forms.ValidationError(_('email already exists.'),code='used email')
        elif self.cleaned_data['email'] == '':
            raise forms.ValidationError(_('This field is required.'),code='empty email')

        return self.cleaned_data['email']

class UserChangeFormUniqueEmail(forms.ModelForm):
    """Change user values."""
    class Meta:
        model = User
        fields = ['first_name','last_name','email']

CicloviaProgram/templates/ciclovia/cambiarContrasenaExito.html
{% extends "ciclovia/base.html" %}

{% comment %}
	Para la codificación en PyCharm
	<head>
		<meta charset="UTF-8">
	</head>
{% endcomment %}

{% block title %}Pagina de {{ request.user.get_username }}{% endblock title %}

{% block content %}

    <div class="container">
        <h1>Cambiar contraseña</h1>
        <p class="alert alert-success">Contraseña cambiada exitosamente.</p>
    </div>

{% endblock content %}

CicloviaProgram/templates/ciclovia/detail.html
{% extends "ciclovia/base.html" %}

{% comment %}
	Para la codificación en PyCharm
	<head>
		<meta charset="UTF-8">
	</head>
{% endcomment %}

{% block content %}
	<div class="container theme-showcase" role="main">
		<div class="page-header">
			<h1>Información detallada</h1>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h3 class="panel-title">Detalle Ciclovía</h3>
					</div>
					<div class="panel-body">
						<table class="table table-striped">
							<thead>
								<tr>
									<th align="center">Información</th>
									<th align="center">Valor</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td align="center">Nombre</td>
									<td align="center">{{ciclovia.name}}</td>
								</tr>	
								<tr>
									<td align="center">Lugar</td>
									<td align="center">{{ciclovia.place}}</td>
								</tr>	
								<tr>
									<td align="center">Horario</td>
									<td align="center">{{ciclovia.start_hour| floatformat:0}}:00 - {{ciclovia.end_hour | floatformat:0}}:00</td>
								</tr>	
								<tr>
									<td align="center">Número de trayectos</td>
									<td align="center">{{ciclovia.num_tracks}}</td>
								</tr>
								{% if ciclovia.arrivals_loaded %}
									<tr>
										<td align="center">Trayecto de referencia</td>
										<td align="center">{{ciclovia.reference_track}}</td>
									</tr>
									<tr>
										<td align="center">Hora de referencia</td>
										<td align="center">{{ciclovia.reference_hour}}</td>
									</tr>
									<tr>
										<td align="center">Tasa de arribos de referencia</td>
										<td align="center">{{ciclovia.reference_arrival_rate}}</td>
									</tr>
								{% endif %}
							</tbody>
						</table>					 
					</div>
				</div>
			</div>			
			<div class="col-md-7">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h3 class="panel-title">Detalle Trayectos</h3>
					</div>
					<div class="panel-body">
						<table class="table table-striped">
							<thead>
								<tr>
									<th align="center">#</th>
									<th align="center">Longitud</th>
									{% if ciclovia.arrivals_loaded %}
										<th align="center">Proporción de arribos</th>
									{% endif %}
									<th align="center">Número de paradas</th>
									<th align="center">Tiene pendiente</th>
									<th align="center">Número de semáforos</th>
									<th align="center">Vecinos</th>
								</tr>
							</thead>
							<tbody>
								{% for track in ciclovia.track_set.all %}
									<tr>
										<td align="center">{{track.id_track}}</td>
										<td align="center">{{track.distance}}</td>
										{% if ciclovia.arrivals_loaded %}
											<td align="center">{{track.arrival_proportion | floatformat:2}}</td>
										{% endif %}
										<td align="center">{{track.number_of_semaphores}}</td>
										{% if track.hasSlope == 0 %}
											<td align="center">No</td>
										{% elif track.hasSlope == 1 %}
											<td align="center">Media</td>
										{% else %}
											<td align="center">Alta</td>
										{% endif %}
										<td align="center">{{track.quality_of_track}}</td>
										<td align="center"><a href="{% url 'CicloviaProgram:detailNeighboor' ciclovia.id track.id %}">Ver vecinos</a></td>
									</tr>
								{% endfor %}
						</table>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			{% if ciclovia.arrivals_loaded %}
				<div class="col-md-4">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title">Ver información de arribos</h3>
						</div>
						<div class="panel-body">
							<p>En esta sección se puede ver la información ingresada de los arribos de la ciclovía.</p>
							<p><a href="{% url 'CicloviaProgram:detailArrival' ciclovia.id %}" class="btn btn-primary">Ver arribos &raquo;</a></p>
						</div>
					</div>
				</div>
			{% else %}
				<div class="col-md-4">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title">Ingresar información de arribos</h3>
						</div>
						<div class="panel-body">
							<p>En esta sección se puede ingresar la información que se va a utilizar para los arribos de la ciclovía (necesarios para la simulación).</p>
							<p><a href="{% url 'CicloviaProgram:uploadArrivalInfoForm' ciclovia.id %}" class="btn btn-primary">Cargar &raquo;</a></p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title">Ingresar información de arribos (archivo XML)</h3>
						</div>
						<div class="panel-body">
							<p>En esta sección se puede ingresar la información que se va a utilizar para los arribos de la ciclovía (necesarios para la simulación) por medio de un archivo XML.</p>
							<p><a href="{% url 'CicloviaProgram:uploadArrivalInfo' ciclovia.id %}" class="btn btn-primary">Cargar &raquo;</a></p>
						</div>
					</div>
				</div>
			{% endif %}
		</div>
		<h2>Grafo de la ciclovía</h2>
		<div class="row">
			<img class="img-responsive img-rounded" src="{% url 'CicloviaProgram:graph' %}?ciclovia_id={{ ciclovia.id }}">
		</div>
		<div class="page-header">
			<h1>Acciones</h1>
		</div>
		<div class="row">
			{% if ciclovia.arrivals_loaded %}
				<div class="col-md-4">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title">Simular</h3>
						</div>
						<div class="panel-body">
							<p>En esta sección se ejecuta la simulación.</p>
							<p><a href="{% url 'CicloviaProgram:simulationResults' ciclovia.id %}" class="btn btn-primary">Ejecutar &raquo;</a></p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title">Validar</h3>
						</div>
						<div class="panel-body">
							<p>En esta sección se valida la simulación</p>
							<p><a href="{% url 'CicloviaProgram:simulationResultsValidation' ciclovia.id %}" class="btn btn-primary">Validar &raquo;</a></p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title">Simulación Inversa</h3>
						</div>
						<div class="panel-body">
							<p>En esta sección puede ejecutar una simulación inversa para calcular la información de arribos</p>
							<p><a href="{% url 'CicloviaProgram:inverseSimulation' ciclovia.id %}" class="btn btn-primary">Configurar &raquo;</a></p>
						</div>
					</div>
				</div>
			{% endif %}
		</div>
		<div class="row">
			{% if ciclovia.arrivals_loaded %}
				<div class="col-md-4">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title">Ver resultados históricos</h3>
						</div>
						<div class="panel-body">
							<p>En esta sección se pueden ver los resultados de la simulación.</p>
							<form action="{% url 'CicloviaProgram:simulationResultsOld' ciclovia.id %}" method="GET">
								{% if resultset %}
									<div class="form-group">
										<select class="form-control" name="results_id">
											{% for result in resultset %}
												<option value="{{ result.id }}">{{ result }}</option>
											{% endfor %}
										</select>
									</div>
									<div class="form-group">
										<input class="btn btn-primary" type="submit" value="Ver resultados &raquo;">
									</div>
								{% else %}
									<p class="text-info"><b>No hay simulaciones</b></p>
								{% endif %}
							</form>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title">Ver resultados históricos validación</h3>
						</div>
						<div class="panel-body">
							<p>En esta sección se pueden ver los resultados de la validación.</p>
							<form action="{% url 'CicloviaProgram:simulationResultsValidationOld' ciclovia.id %}" method="GET">
								{% if resultset2 %}
									<div class="form-group">
										<select class="form-control" name="results_id">
											{% for result in resultset2 %}
												<option value="{{ result.id }}">{{ result }}</option>
											{% endfor %}
										</select>
									</div>
									<div class="form-group">
										<input class="btn btn-primary" type="submit" value="Ver resultados &raquo;">
									</div>
								{% else %}
									<p class="text-info"><b>No hay validaciones</b></p>
								{% endif %}
							</form>
						</div>
					</div>
				</div>
			{% endif %}
			<div class="col-md-4">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h3 class="panel-title">Editar ciclovía</h3>
					</div>
					<div class="panel-body">
						<p>En esta seccion se puede editar la información de la ciclovía y sus trayectos.</p>
						<p><a class="btn btn-primary" href="{% url 'CicloviaProgram:editCiclovia' ciclovia.id %}">Editar &raquo;</a></p>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h3 class="panel-title">Borrar ciclovía</h3>
					</div>
					<div class="panel-body">
						<p>Para borrar la ciclovía presione el siguiente botón.</p>
						<a class="btn btn-primary" href="{% url 'CicloviaProgram:borrarCiclovia' ciclovia.id %}"
						title="Eliminar ciclovia" onclick="return confirm('¿Seguro que desea borrar la ciclovía?')">
							Borrar ciclovía &raquo;
						</a>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h3 class="panel-title">Copiar ciclovía</h3>
					</div>
					<div class="panel-body">
						<p>Para crear una copia de la ciclovía ingrese el nombre de la copia y presione el botón. </p>
						<form action="{% url 'CicloviaProgram:copyCiclovia' ciclovia.id %}" method="POST">
							{% csrf_token %}
							<div class="form-group">
								<label class="control-label" for="id_nombre" >Nombre:</label>
								<input class="form-control" type="text" id="id_nombre" name="nombre" />
							</div>
							<div class="form-group">
								<input class='btn btn-primary' type="submit" value="Copiar &raquo;">
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}       

CicloviaProgram/templates/ciclovia/passwordResetDone.html
{% extends "ciclovia/base.html" %}

{% comment %}
	Para la codificación en PyCharm
	<head>
		<meta charset="UTF-8">
	</head>
{% endcomment %}

{% block content %}

    <div class="container">
        <h1>Restablecer contraseña</h1>
		<p class="text-info">Si había alguna cuenta asociada al correo,
            se ha enviado el vínculo para restablecer la constraseña.</p>
    </div>

{% endblock content %}